openapi: 3.0.3
info:
  title: Counter Service
  version: 1.0.0
paths:
  /count:
    get:
      summary: Get current count
      responses:
        '200':
          description: Current count
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
  /increment:
    post:
      summary: Increment count
      responses:
        '200':
          description: Count incremented
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer